# Generated by Django 3.2.8 on 2022-01-11 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220111_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='level',
        ),
        migrations.AddField(
            model_name='material',
            name='level',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='api.level'),
            preserve_default=False,
        ),
    ]
