# Generated by Django 3.2.8 on 2022-01-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20220119_0954'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.AddField(
            model_name='quizpack',
            name='questions',
            field=models.ManyToManyField(to='api.Question'),
        ),
    ]
