# Generated by Django 3.2.8 on 2022-01-19 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_question_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ans',
            field=models.CharField(choices=[('A', 'op1'), ('B', 'op2'), ('C', 'op3'), ('D', 'op4')], default='A', max_length=1),
        ),
    ]
