# Generated by Django 3.2.8 on 2022-01-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_question_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizpack',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
