# Generated by Django 3.2.8 on 2022-01-23 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_questionattempt_quizattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionattempt',
            name='status',
            field=models.BooleanField(null=True),
        ),
    ]
